config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :campaigns
  resources :charges
  resources :photos

  post 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get "/tagged/:id" => "campaigns#tag", :as => :tagged_posts

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # devise_for :users
  resources :users

  get 'users/sign_out' => 'users/sessions#destroy'

  devise_scope :user do
	  get "users/sign_in", :to => "devise/sessions#new"
	  get 'users/sign_out', :to => 'devise/sessions#destroy'
	end

  get "/campaigns/:slug/photos/:id" => "photos#show", as: "campaign_photo"

  root to: 'visitors#index'
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user

mount_uploader :image, ImageUploader


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :bio, :image, :image_url, :date_of_birth, :location, :website)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :bio %>
    <%= f.input :image %>
    <%= f.input :image_url %>
    <%= f.input :date_of_birth %>
    <%= f.input :location %>
    <%= f.input :website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bio</th>
      <th>Image</th>
      <th>Image url</th>
      <th>Date of birth</th>
      <th>Location</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.image %></td>
        <td><%= profile.image_url %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= profile.location %></td>
        <td><%= profile.website %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<h1>
  <%= @profile.user.name %>
  <small><%= @profile.fb_image_url %></small>
</h1>

<div class="col-md-12 row" >
  <div class="col-md-8">
    <div class="well">
      <%= @profile.bio %>
      </div>

      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#photos" role="tab" data-toggle="tab">Photos (<%= @profile.user.photos.count %>)</a></li>
        <li><a href="#campaigns" role="tab" data-toggle="tab">Campaigns (<%= @profile.user.campaigns.count %>)</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="photos">
            <ul> 
              <% @profile.user.photos.each do |photo| %>
                <li class="pull-left"><%= link_to image_tag(photo.image.url(:small), :class => "thumbnail"), photo %></li>
              <% end %>
            </ul>
          </div>
          <div class="tab-pane" id="campaigns">
          <br/>
            <% @profile.user.campaigns.each do |campaign| %>
              <div class="clearfix col-md-12 row"> 
                <div class="col-md-3 pull-left">
                  <%= link_to image_tag(campaign.image.url(:small), :class => "thumbnail "), campaign %>
                </div>
                  <div class="col-md-9 pull-left">
                  <h3><%= link_to campaign.name, campaign %></h3>
                  <p class="well"> <%= truncate(campaign.description, length: 100) %></p>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
  </div>
  <div class="col-md-4" >
    <%= image_tag(@profile.fb_image_url || @profile.image.url, :class => "img-circle") %>

    <p>
      <%= @profile.location %>
    </p>

    <p>
      <%= link_to @profile.website, @profile.website, :target => "" %>
    </p>

</div>


<% if current_user && current_user == @profile.user or current_user && current_user.admin? %>
<%= link_to 'Edit', edit_profile_path(@profile), :class => "btn btn-sm btn-default pull-right" %>
<% end %>