config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :campaigns
  resources :charges
  resources :photos

  post 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get "/tagged/:id" => "campaigns#tag", :as => :tagged_posts

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # devise_for :users
  resources :users

  get 'users/sign_out' => 'users/sessions#destroy'

  devise_scope :user do
	  get "users/sign_in", :to => "devise/sessions#new"
	  get 'users/sign_out', :to => 'devise/sessions#destroy'
	end

  get "/campaigns/:slug/photos/:id" => "photos#show", as: "campaign_photo"

  root to: 'visitors#index'
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	paginates_per 10

	mount_uploader :image, ImageUploader
		
	belongs_to :user
	belongs_to :campaign

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!, except: [:show, :index, :create]	
	after_action :donation_email, only: :create


	def index
		@photos = Photo.all
	end

	def show
		@photo = Photo.find(params[:id])
		@photo.views += 1
		@photo.save
	end

	def new
	end

	def edit
		@photo = Photo.find(params[:id])
		authorize @photo
	end

	def create
		  # Amount in cents

		  @amount = params[:amount].to_i

		  if @amount < 2
		  	@amount = 2
		  end

		  @photo = Photo.new()
		  if current_user
			  @photo.user_id = current_user.id
		  end
		  @photo.title = params[:title]
		  @photo.image = params[:image]
		  @photo.url = params[:url]
		  @photo.campaign_id = params[:campaign_id].to_i
		  @photo.paid = @amount
		  @photo.save

		  @donation = Donation.new()
		  @donation.amount = @amount
		  @donation.stripe_email = params[:stripeEmail]
		  @donation.photo_id = @photo.id
		  if current_user
			  @donation.user_id = current_user.id
		  end
		  @donation.campaign_id = params[:campaign_id].to_i
		  @donation.save

		  customer = Stripe::Customer.create(
		    :email => params[:stripeEmail],
		    :card  => params[:stripeToken]
		  )

		  charge = Stripe::Charge.create(
		    :customer    => customer.id,
		    :amount      => @amount * 100,
		    :description => 'Phunder App',
		    :currency    => 'usd'
		  )

		redirect_to photo_path(@photo)

		rescue Stripe::CardError => e
		  flash[:error] = e.message
		  redirect_to photo_path(@photo)

		 redirect_to :back
	end


	def update
		@photo = Photo.find(params[:id])
    
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def donation_email
  	@campaign = Campaign.find(params[:campaign_id].to_i)
      UserMailer.donation_email(@campaign.user.email, @campaign.user, @campaign, @photo).deliver
      UserMailer.donation_email("phunderapp@gmail.com", User.first, @campaign, @photo).deliver
  end


	private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image, :user_id, :campaign_id, :url, :visits, :clicks, :paid, :hidden)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="well form-inline" %>
  <%= simple_form_for(@photo,  :class => "form" ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs form-group">

      <%= f.input :title %>
      <br/>
      <%= f.label :hidden %>
      <%= f.check_box :hidden %>
      <br/>
      <%= f.input :url %>
      
    </div>
    <hr/>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

</div>

app/views/photos/create.html.erb
<h2>Thanks, you paid <strong>$<%= @photo.paid %></strong>!</h2>

<h3>
<%= link_to "View your Photo contribution", campaign_photo_path(:slug => params[:campaign_id], :id => @photo.id), :class => "btn btn-default btn-lg" %>
</h3>

<h3>
<%= link_to "Back to the Campaign page", campaign_path(params[:campaign_id]), :class => "btn btn-default btn-lg" %>
</h3>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos<h1/>
<div class="row col-md-12">
<% @photos.reverse.each do |photo| %>
	<div class="col-md-3">
	<%= link_to image_tag(photo.image.url(:square), :class=>"thumbnail pull-left"), photo %>
	</div>
<% end %>

app/views/photos/show.html.erb
<div class="clearfix col-md-12">
		
	<h1>
		<% if @photo.title != nil %>
		<%= link_to @photo.title, @photo.url, :target => "_blank" %>
		<% end %>

		<small>
			<% if @photo.user != nil %>
				<%= @photo.user.name %>
			<% end %>
		</small>
	</h1>

	<h2>
		Campaign: <%= link_to @photo.campaign.name, @photo.campaign  %>
	</h2>
	<hr/>
	<div class="col-md-4 row">
		<%= button_to "Donate & Upload", @photo.campaign, :class => "btn btn-success btn-lg btn-block", :method => :get %>
		<br/>
		<div class="panel panel-default">
		    <div class="panel-heading">
			    <h4>Photo Stats</h4>
		    </div>
		    <div class="panel-body">
		    	<h4>
			    	<label class=" label  label-success">
					    <i>$</i> <%= @photo.paid %> Donated
					</label><br/><br/>
				    <label class="label label-lg label-info">
			    		<i class="glyphicon glyphicon-eye-open"></i> <%= @photo.views %> Views
					</label>
				</h4>
		    </div>
	    </div>
		
		<div class="panel panel-default">
	    <div class="panel-heading">
	           <h4>
	              Share
	            </h4>
	        </div>
	        <div class="panel-body">
			<%= render_shareable :turbolinks => true, :buttons => ['facebook', 'twitter'], :facebook=> {:send=> 'true', :url=> '#{photo_url(@photo)}'}, :twitter => {:via => 'phunderapp', :text  => "New Photo: #{@photo.title} for the #{@photo.campaign.name} @phunderapp campaign - ", :hashtags => @photo.campaign.hashtag }  %>
			</div>
		</div>
		<% if current_user && current_user.admin? %>
		<div class="" >
			<%= link_to "Edit", edit_photo_path(@photo), :class => "btn btn-default btn-xs" %>
		</div>
		<% end %>
	</div>
	<div class="col-md-8">
		<%#= image_tag(@photo.image.url(), :class => "pull-left") %>
		<div class="clearfix">
		<%= link_to cl_image_tag(@photo.image.url().split("/").last,  :transformation=>[
        {:width=>400, :crop=>:scale},
        {:opacity=>50, :overlay=>"lightning-logo_black", :crop=>:scale, :gravity=>:north_west, :flags=>:relative, :x=>5, :y=>5},
        {:color=>"#303030", :overlay=>"text:Helvetica_20_bold:@phunderapp", :x=>10, :y=>5, :gravity=>:south_west, :opacity => 50},
        {:opacity=>50, :overlay=> @photo.campaign.water_mark.url(:water_mark).split("/").last, :crop=>:scale, :gravity=>:north_east, :flags=>:relative, :x=>5, :y=>5, :size => "50"},
        {:color=>"#303030", :overlay=>"text:Helvetica_20_bold:%23#{@photo.campaign.hashtag}", :x=>10, :y=>5, :gravity=>:south_east, :opacity => 50}
        ], :class=>"pull-left thumbnail"), @photo.url, :target => "_blank" %>

        </div>
		<div class="pull-left">
			<h3>Comments<h3/>
			<hr/>
			<div class="fb-comments" data-href="<%= photo_url(@photo)%>" data-numposts="5" data-colorscheme="light"></div>
		</h3>
		</div>
	</div>

</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=615925001838726&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<style type="text/css">
  body {
     background-image: url("<%= @photo.campaign.banner.url(:background) %>");
  }

</style>