config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :campaigns
  resources :charges
  resources :photos

  post 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get "/tagged/:id" => "campaigns#tag", :as => :tagged_posts

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # devise_for :users
  resources :users

  get 'users/sign_out' => 'users/sessions#destroy'

  devise_scope :user do
	  get "users/sign_in", :to => "devise/sessions#new"
	  get 'users/sign_out', :to => 'devise/sessions#destroy'
	end

  get "/campaigns/:slug/photos/:id" => "photos#show", as: "campaign_photo"

  root to: 'visitors#index'
  
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  acts_as_taggable

	mount_uploader :image, ImageUploader

	mount_uploader :banner, ImageUploader

  mount_uploader :water_mark, ImageUploader

	belongs_to :user
	has_many :photos

  paginates_per 10

  extend FriendlyId
  friendly_id :name, use: :slugged

  def views
    @views = 0

    self.photos.where(:hidden => false).each do |photo|
      @views = @views + photo.views
    end

    return @views
  end

  def percent
      running = 0
      self.photos.where(:hidden => false).each do |photo| 
        running = running + photo.paid
      end

    return  ((running.to_f / self.target.to_f) * 100).round(2)
  end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image, :user_id, :campaign_id, :paid)
    end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :tag]
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  require 'rails_autolink'


  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show

      Rails.configuration.stripe = {
      :publishable_key => @campaign.user.stripe_publishable_key || ENV['PUBLISHABLE_KEY'] ,
      :secret_key      => @campaign.user.stripe_secret_key || ENV['SECRET_KEY']
      }

      Stripe.api_key = Rails.configuration.stripe[:secret_key]
      # Stripe.api_key = @campaign.user.stripe_secret_key

      @photos = @campaign.photos.where(:hidden => false).order('views DESC')

      @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(9)

  end

  def tag
    @campaigns = Campaign.tagged_with(params[:id]).page(params[:all])

    @tags = Campaign.tag_counts_on(:tags)
    render :action => 'index'
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
    authorize @campaign
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :description, :user_id, :target,
       :live, :price, :image, :banner, :end_date, :hashtag, :water_mark, :tag_list)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<div class="well form-inline" %>
  <%= simple_form_for(@campaign,  :class => "form" ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs form-group">
      <%= f.label :name %><br/>
      <%= f.text_area :name, :cols => "60", :rows => 1 %>
      <p class="help-block">Choose a catchy title for your campaign.</p>
      <br/>
      <%= f.label :description, "About" %>
      <br/>
      <%= f.text_area :description, :cols => "60", :rows => "10" %>
      <p class="help-block">Tell your donars about this campaign.</p>
      <%= f.input :user_id, as: :hidden %>
      <br/>
      <%= f.label :target %>
      <%= f.number_field :target, :min => 1 %>
      <p class="help-block">Set a total campaign target.</p>
      <br/>
      <%= f.input :hashtag, :placeholder => "hashtag" %>
      <p class="help-block">Set a #hashtag for the campaign.</p>
      <br/>
      <%= f.label :price %>
      <%= f.number_field :price, :min => 1, :placeholder => 5 %>
      <p class="help-block">Set a suggested ammount to give.</p>
      <br/>
      <%= f.label :image, "Image" %>
      <%= f.file_field :image %>
      <p class="help-block">The main image for the campaign, this could be an example for people to upload.</p>
      <p class="help-block pul-left"><%= image_tag(@campaign.image.url(:thumb)) %></p>
      <br/>
      <%= f.label :banner, "Banner" %>
      <%= f.file_field :banner %>
      <p class="help-block">The background image for your campaign page.</p>
      <p class="help-block pul-left"><%= image_tag(@campaign.banner.url(:thumb)) %></p>
      <br/>
      <%= f.label :water_mark, "Water Mark" %>
      <%= f.file_field :water_mark %>
      <p class="help-block">Upload a transparent png 50px X 50px</p>
      <p class="help-block pul-left"><%= image_tag(@campaign.water_mark.url(:thumb)) %></p>

      <% if current_user && current_user.admin? %>
        <hr/>
        <%= f.input :end_date %>
        <br/>
        <%= f.input :live %>
        <b/>
        <%= f.input :tag_list %>
      <% end %>
    </div>
    <hr/>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

</div>

app/views/campaigns/_social_meta.html.erb
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@phunderapp">
<meta name="twitter:title" content="<%= @campaign.name %>">
<meta name="twitter:description" content="<%= @campaign.description %>">
<meta name="twitter:creator" content="@punderapp">
<meta name="twitter:image:src" content="<%= @campaign.image.url(:square) %>">
<meta name="twitter:domain" content="phunderapp.com">
<meta property="og:title" content="<%= @campaign.name %>" />
<meta property="og:url" content="http://phunderapp.com/campaigns/<%= @campaign.id %>" />
<meta property="og:image" content="<%= @campaign.image.url(:square) %>" />

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>


<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<h1>
All Campaigns
<br/>
	<% if params[:id] %>
	<small>
		Tagged: <%= params[:id] %>
	</small>
	<% end %>
</h1>
<hr/>
<div class="clearfix row">
    <% @campaigns.each do |campaign| %>
        	<div class="col-md-4">
        	<%= link_to image_tag(campaign.image.url(), :class => "pull-left thumbnail img-rounded"), campaign %>
        	</div>
        	<div class="col-md-8">
	        	<h3>
	        	<%= link_to campaign.name, campaign %>
	        	</h3>
	        	<p class="well">
		        	<%= campaign.description %>
		        </p>
		        <ul class='clearfix pull-left' >
						    <% campaign.photos.where(:hidden => false).limit(10).reverse.each do |photo| %>
						      <%= link_to image_tag(photo.image.url(:thumb), :class => "pull-left thumbnail img-rounded", :style => "margin-right:10px; border: 2px, solid grey;"), campaign_photo_path(:slug => campaign.slug, :id => photo.id) %>
						    <% end %>
				 </ul>  
		        <%= button_to "Donate", campaign, :class => "btn btn-success btn-lg btn-block", :method => :get %>
        	</div>
    <% end %>
</div>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form' %>

app/views/campaigns/show.html.erb
<% content_for :description do %>
  <%= @campaign.description %>
<% end %>

<% content_for :head do %>
  <%= render 'social_meta' %>
<% end %>


<article style="">
  <h1>
  <span class="pull-right">
      <p class="label label-success">
        <strong>Target:
          $<%= @campaign.target %>
        </strong>
      </p>
      <p class="label label-info">
        <strong><%= @campaign.percent %>%</strong>
      </p>
  </span>
  
    <%= @campaign.name.split.map(&:capitalize).join(' ') %>
    (#<%= @campaign.hashtag %>) 
  <br/>
   <small>
  <% if @campaign.user.name != nil %>
    by <%= link_to @campaign.user.name, profile_path(@campaign.user) %>
    <% end %>
    </small>
  </h1>
  <hr/>
  <div class="clearfix row" >
  

  <div class="pull-left col-md-8">
    <p class="well clearfix">
    <%= auto_link(@campaign.description.gsub(/\n/, '<br/>').html_safe, :all, :target => "_blank") %>
    <br/>
    </p>

    <div class="panel panel-info">
      <div class="panel-heading">
         <h3>
           <span class="label label-info pull-right">
              Minimum:
              $<%= number_with_precision(@campaign.price, :precision => 2) %>
            </span>
            Donate & Upload
            
          </h3>
      </div>
      <div class="panel-body">
      <%= form_tag ({:controller => "photos", :action => "create"}), :enctype =>"multipart/form-data" do %>
        
        <div class="input-group">
          <span class="input-group-addon">$</span>
            <%= number_field_tag :amount, number_with_precision(@campaign.price, :precision => 2), :class=> "form-control", :width => "50%", :min => number_with_precision(@campaign.price, :precision => 2), :step => 1 %>
        </div>
        <br/>
        <div class="clearfix">
          <div class="pull-left">
          <%= file_field_tag "image" , :class => "btn btn-default" %>
          <p class="help-block">Select a photo relevant to this campaign (optional).</p>
          <%= hidden_field_tag :campaign_id, @campaign.id %>
          </div>
          <!-- <div class="pull-left" style="margin-left: 20px;">
            <%#= label :url, "Url : " %>
            <%#= text_field_tag :url %>
            <p class="help-block">(Optional)</p>
          </div> -->
        </div>
        <br/>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= @campaign.user.stripe_publishable_key %>"
                data-description="Donation to <%= @campaign.name %>"
                data-amount=""
                data-image="<%= @campaign.image.url(:thumb) %>">
        </script>
      <% end %>
      </div>
  </div>
    <%# if @photos.where(:hidden => false) !=  [] %>
      <h3>Photos</h3>
      <hr/>
      <% @photos.each do |photo| %>
        <div class="col-md-4 pull-left text-center">
          <%= link_to cl_image_tag(photo.image.url(:square), :class => "img-rounded pull-left thumbnail", :width => "200px"), campaign_photo_path(:slug => @campaign.slug, :id => photo.id) %>
          <br/>
          <p class="pull-left">
            <h3><%= link_to "View", campaign_photo_path(:slug => @campaign.slug, :id => photo.id), :class => "btn btn-sm btn-default" %></h3>
            <label class="label label-info">
              <i class="glyphicon glyphicon-eye-open"></i> <%= photo.views %> Views
            </label>
          </p>
        </div>
      <% end %>
      <br/>
      <div class="pull-left clearifx" >
      <%= paginate @photos %>
      </div>
    <%# end %>

  </div>

  <div class="pull-left col-md-4">
  <p>

       <%= cl_image_tag(@campaign.image.url().split("/").last,  :transformation=>[
        {:width=>400, :crop=>:scale},
        {:opacity=>50, :overlay=>"lightning-logo_black", :crop=>:scale, :gravity=>:north_west, :flags=>:relative, :x=>5, :y=>5},
        {:color=>"#191919", :overlay=>"text:Helvetica_20_bold:@phunderapp", :x=>10, :y=>5, :gravity=>:south_west, :opacity => 50},
         {:opacity=>50, :overlay=> @campaign.water_mark.url(:water_mark).split("/").last, :crop=>:scale, :gravity=>:north_east, :flags=>:relative, :x=>5, :y=>5, :size => "50"},
        {:color=>"#191919", :overlay=>"text:Helvetica_20_bold:%23#{@campaign.hashtag}", :x=>10, :y=>5, :gravity=>:south_east, :opacity => 50}
        ], :class=>"img-rounded thumbnail", :width => "360px") %>


  </p>
  <br/>
  <div class="panel panel-default">
    <div class="panel-heading">
           <h4>
              Data
            </h4>
        </div>
        <div class="panel-body">
        <h4>
          <label class="label label-default">
            <i class="glyphicon glyphicon-camera"></i>
            <%= @campaign.photos.where(:hidden => false).count %> photos
          </label>
          <br/><br/>
          <label class="label label-info">
            <i class="glyphicon glyphicon-eye-open"></i>
            <%= @campaign.views %> views
          </label>
          <br/><br/>
          <% @campaign.tag_list.each do |tag| %>
            <label class="label label-default">
              <i class="glyphicon glyphicon-tag"></i>
              <%= link_to tag, tagged_posts_path(tag) %>
            </label>
            &nbsp;
          <% end %>
        </h4>
        </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
           <h4>
              Share
            </h4>
        </div>
        <div class="panel-body">
        <%= render_shareable :turbolinks => true, :buttons => ['facebook', 'twitter'], :facebook=> {:send=> 'true', :url=> '#{campaign_path(@campaign)}'}, :twitter => {:via => 'phunderapp', :text  => "Support the #{@campaign.name} campaign - ", :hashtags => @campaign.hashtag } %>
        </div>
    </div>
    <% if current_user && current_user.admin? || current_user == @campaign.user %>
      <%= link_to "Edit", edit_campaign_path(@campaign), :class => "btn btn-default btn-xs" %>    
      <%= link_to "Delete", campaign_path(@campaign), :method => "DELETE", confirm: "Are you sure?", :class => "btn btn-danger btn-xs" %>
    <% end %>
  </div>
  </div>
</article>

<style type="text/css">
  body {
    background-image: url("<%= @campaign.banner.url(:background) %>");
  }

</style>