config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :campaigns
  resources :charges
  resources :photos

  post 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get "/tagged/:id" => "campaigns#tag", :as => :tagged_posts

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # devise_for :users
  resources :users

  get 'users/sign_out' => 'users/sessions#destroy'

  devise_scope :user do
	  get "users/sign_in", :to => "devise/sessions#new"
	  get 'users/sign_out', :to => 'devise/sessions#destroy'
	end

  get "/campaigns/:slug/photos/:id" => "photos#show", as: "campaign_photo"

  root to: 'visitors#index'
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', width: 30), root_path, class: 'navbar-brand' %>
      <a href="<%= root_path %>" class="navbar-brand" style="color:white; font-size:20px;" />Phunder App</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=> "delete" %></li>
  <% if current_user.stripe_secret_key == nil %>
    <li><a href="<%= user_omniauth_authorize_path(:stripe_connect) %>" ><button class="btn btn-dropbox" ><i class="fa fa-stripe"></i> Connect Stripe</button></a></li>
  <% else %>
    <li class=""><%= link_to 'New Campaign', new_campaign_path %></li>
  <% end %>
<% else %>
  <li><%#= link_to 'Sign in', new_user_session_path %></li>
  <li><%#= link_to 'Sign up', new_user_registration_path %></li>
  <li><a href="<%= user_omniauth_authorize_path(:facebook) %>" ><button class="btn btn-facebook" ><i class="fa fa-facebook"></i> | Sign in with Facebook</button></a></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Phunder" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Phunder" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" >
      <%= render 'layouts/messages' %>
      <div class="container">
       <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/layouts/yeti.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "phunder" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Phunder" %>">
    <%= content_for?(:head) ? yield(:head) : "" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "yeti", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>
    <%= render 'layouts/messages' %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container" >
      <div class='text-center' class="leaderboard">
       
    </div>
  </div>
<br/>
    <main role="main" class="row col-md-12" >
      <div class="container">
       <%= yield %>
       </div>
    </main>
    <div class="container" >
      <div class='text-center' class="leaderboard">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- Leaderboard -->
      <ins class="adsbygoogle"
           style="display:inline-block;width:728px;height:90px"
           data-ad-client="ca-pub-1304865037882733"
           data-ad-slot="1940508116"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-53711043-1', 'auto');
      ga('send', 'pageview');

    </script>
    
  </body>
</html>